package dependencygraph.vccl.copynumber.node;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import utils.FXUtils;

public class DAGNodeController<V,E>{
	public static final String FXML_FILE_DIR_STRING = "/dependencygraph/vccl/copynumber/node/DAGNode.fxml";
	
	/////////////////////////////
	private DAGNodeManager<V,E> manager;

	void setManager(DAGNodeManager<V,E> manager) {
		this.manager = manager;
		this.inforLabel.setText(this.manager.getNodeInforString());
		
		if(this.getManager().getCopyNumber()==0) {
			FXUtils.set2Disable(this.decreaseByOneButton, true);
		}
	}
	
	/**
	 * @return the manager
	 */
	public DAGNodeManager<V, E> getManager() {
		return manager;
	}
	
	public Pane getRootNodeContainer() {
		return this.nodeRootStackPane;
	}
	
	/**
	 * set the status to assignable so that the copy number can be changed;
	 */
	void setToAssignable() {
		FXUtils.set2Disable(this.copyNumberAssignmentControllHBox, false);
		//if current copy number is 0, set decreaseByOneButton to disabled
		if(this.getManager().getCopyNumber()==0) {
			FXUtils.set2Disable(this.decreaseByOneButton, true);
		}
	}
	
	/**
	 * set the status to un-assignable so that the copy number cannot be changed;
	 * note that when un-assignable, copy number must be 0;
	 */
	void setToUnAssignable() {
		FXUtils.set2Disable(this.copyNumberAssignmentControllHBox, true);
	}
	
	void setDecreaseByOneButtonDisable(boolean disabled) {
		FXUtils.set2Disable(this.decreaseByOneButton, disabled);
	}
	
	void setCopyNumberTextField(int copyNumber) {
		this.copyNumberTextField.setText(Integer.toString(copyNumber));
	}
	
	void setModifiable(boolean modifiable) {
		FXUtils.set2Disable(this.copyNumberAssignmentControllHBox, !modifiable);
	}
	
	////////////////////
	@FXML
	public void initialize() {
		// TODO Auto-generated method stub
	}
	
	@FXML
	private StackPane nodeRootStackPane;
	@FXML
	private Label inforLabel;
	@FXML
	private TextField copyNumberTextField;
	@FXML
	private HBox copyNumberAssignmentControllHBox;
	@FXML
	private Button increaseByOneButton;
	@FXML
	private Button decreaseByOneButton;
	@FXML
	private Button viewNodeDetailsButton;
	
	// Event Listener on Button[#increaseByOneButton].onAction
	@FXML
	public void increaseByOneButtonOnAction(ActionEvent event) {
		this.getManager().getHostDAGNodeCopyNumberAssignmentManager().getController().enableFinishAndCancelButton();
		
		int newCopyNumber = this.manager.getCopyNumber()+1;
//		this.copyNumberTextField.setText(Integer.toString(newCopyNumber));
		this.manager.setCopyNumber(newCopyNumber);
	}
	
	// Event Listener on Button[#decreaseByOneButton].onAction
	@FXML
	public void decreaseByOneButtonOnAction(ActionEvent event) {
		this.getManager().getHostDAGNodeCopyNumberAssignmentManager().getController().enableFinishAndCancelButton();
		
		int newCopyNumber = this.manager.getCopyNumber()-1;
//		this.copyNumberTextField.setText(Integer.toString(newCopyNumber));
		this.manager.setCopyNumber(newCopyNumber);
	}
	
	
	// Event Listener on Button[#viewNodeDetailsButton].onAction
	@FXML
	public void viewNodeDetailsButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
