package builder.visframe.function.composition.originalIndieFIVTypeUtils;

import java.io.IOException;
import java.sql.SQLException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import utils.FXUtils;


/**
 * OriginalIndieFIVTypeEntry can be created or deleted but not modified after creation;
 * @author tanxu
 *
 */
public class OriginalIndieFIVTypeEntryUIController {
	public static final String FXML_FILE_DIR_STRING = "/builder/visframe/function/composition/originalIndieFIVTypeUtils/OriginalIndieFIVTypeEntryUI.fxml";
	
	private OriginalIndieFIVTypeEntryBuilder ownerBuilder;
	
	public void setOwnerBuilder(OriginalIndieFIVTypeEntryBuilder ownerBuilder) {
		this.ownerBuilder = ownerBuilder;
		
		
		//initialization based on owner builder
		
	}

	/**
	 * @return the ownerBuilder
	 */
	public OriginalIndieFIVTypeEntryBuilder getOwnerBuilder() {
		return ownerBuilder;
	}
	
	
	public Parent getRootContainerNode() {
		return this.containerHBox;
	}
	
	public void setModifiable(boolean modifiable) {
		FXUtils.set2Disable(this.deleteButton, !modifiable);
	}
	
	
	void setDeleteDisable(boolean disable) {
		FXUtils.set2Disable(this.deleteButton, disable);
	}
	
	
	void setEmployerFreeInputVariableNum(int num) {
		this.numOfEmployerFIVBuilderTextField.setText(Integer.toString(num));
	}
	

	void setTypeName(String typeName) {
		this.nameTextField.setText(typeName);
	}
	

	void setDeleteButtonDisable(boolean disable) {
		FXUtils.set2Disable(this.deleteButton, disable);
	}


//	void setEditDisable(boolean disable) {
//		this.editButton.setDisable(disable);
//	}
	/////////////////////////////////////////////
	@FXML
	public void initialize() {
		
		
	}
	
	@FXML
	private HBox containerHBox;
	@FXML
	private TextField nameTextField;
	@FXML
	private TextField numOfEmployerFIVBuilderTextField;
	@FXML
	private Button deleteButton;
//	@FXML
//	private Button editButton;
	@FXML
	private Button viewButton;

	// Event Listener on Button[#deleteButton].onAction
	@FXML
	public void deleteButtonOnAction(ActionEvent event) throws SQLException, IOException {
		// TODO Autogenerated
		this.getOwnerBuilder().getHostCompositionFunctionBuilder().deleteOriginalIndieFIVTypeEntryBuilder(this.getOwnerBuilder().getIndependentFreeInputVariableTypeBuilder().getCurrentValue().getName());
		
	}
	
//	// Event Listener on Button[#editButton].onAction
//	@FXML
//	public void editButtonOnAction(ActionEvent event) {
//		// TODO Autogenerated
//	}
	
	
	// Event Listener on Button[#viewButton].onAction
	@FXML
	public void viewButtonOnAction(ActionEvent event) throws SQLException, IOException {
		this.getOwnerBuilder().getIndependentFreeInputVariableTypeBuilder().setModifiable(false);
		
		this.getOwnerBuilder().getIndependentFreeInputVariableTypeBuilder().getIntegrativeUIController().showAndWait(this.getRootContainerNode().getScene().getWindow(), "Original IndependentFreeInputVariableType");
		
	}

}
