package session.serialization.fileformat;

import javafx.fxml.FXML;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.stage.DirectoryChooser;
import javafx.stage.Stage;
import session.serialization.SerializationUtils;
import utils.AlertUtils;
import utils.exceptionhandler.ExceptionHandlerUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import fileformat.FileFormat;
import javafx.event.ActionEvent;

public class ExportFileFormatController {
	public static final String FXML_FILE_DIR_STRING="/session/serialization/fileformat/ExportFileFormat.fxml";
	
	private ExportFileFormatManager manager;
	
	void setManager(ExportFileFormatManager manager) {
		this.manager = manager;
	}
	
	ExportFileFormatManager getManager() {
		return this.manager;
	}
	
	Parent getRootNode() {
		return this.rootContainerVBox;
	}
	
	
	TextField getSelectedFileFormatDataTypeTextField() {
		return this.selectedFileFormatDataTypeTextField;
	}
	TextField getSelectedFileFormatNameTextField() {
		return this.selectedFileFormatNameTextField;
	}
	
	Path getExportDirectoryPath() {
		Path p = Paths.get(this.exportLocationTextField.getText());
		if(Files.notExists(p)) {
			return null;
		}
		
		if(!Files.isDirectory(p)) {
			return null;
		}
		return p;
	}
	

	Stage getStage() throws IOException {
		return (Stage) this.selectedFileFormatNameTextField.getScene().getWindow();
	}
	////////////////////////////////////////////////////
	private DirectoryChooser directoryChooser = new DirectoryChooser();
	
	
	@FXML
	public void initialize() {
		
	}
	
	
	@FXML
	private VBox rootContainerVBox;
	@FXML
	private TextField selectedFileFormatDataTypeTextField;
	@FXML
	private TextField selectedFileFormatNameTextField;
	@FXML
	private Button browseFileformatButton;
	@FXML
	private Button viewSelectedFileFormatDetailButton;
	@FXML
	private TextField exportLocationTextField;
	@FXML
	private Button browseExportLocationButton;
	@FXML
	private Button exportButton;
	@FXML
	private Button cancelButton;
	@FXML
	private Button resetButton;

	// Event Listener on Button[#browseFileformatButton].onAction
	@FXML
	public void browseFileformatButtonOnAction(ActionEvent event) throws IOException {
		try {
			this.getManager().getFileFormatTableViewManager().showWindow(this.getStage());
		}catch(Exception e) {
			ExceptionHandlerUtils.show("ExportFileFormatController.browseFileformatButtonOnAction", e, this.getStage());
		}
	}
	
	// Event Listener on Button[#viewSelectedFileFormatDetailButton].onAction
	@FXML
	public void viewSelectedFileFormatDetailButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#browseExportLocationButton].onAction
	@FXML
	public void browseExportLocationButtonOnAction(ActionEvent event) throws IOException {
		try {
			File selectedDirectory = directoryChooser.showDialog(this.getStage());
			if(selectedDirectory==null) {
				return;
			}
			this.exportLocationTextField.setText(selectedDirectory.toString());
		}catch(Exception e) {
			ExceptionHandlerUtils.show("ExportFileFormatController.browseExportLocationButtonOnAction", e, this.getStage());
		}
	}
	
	// Event Listener on Button[#exportButton].onAction
	@FXML
	public void exportButtonOnAction(ActionEvent event) throws IOException {
		try {
			if(this.getManager().getFileFormatTableViewManager().getSelectedItem()==null) {
				AlertUtils.popAlert("Error", "No FileFormat is selected!");
				return;
			}else if(this.getExportDirectoryPath()==null) {
				AlertUtils.popAlert("Error", "No export directory is selected!");
				return;
				
			}else {
				FileFormat fileFormat = this.getManager().getFileFormatTableViewManager().getSelectedItem();
				Path exportFilePath = Paths.get(this.getExportDirectoryPath().toString(),fileFormat.getName().getStringValue().concat(ExportFileFormatManager.FILE_FORMAT_SERIALIZED_FILE_EXTENSTION));
				SerializationUtils.serializeToFile(exportFilePath, fileFormat);
				
				this.getStage().close();
			}
		}catch(Exception e) {
			ExceptionHandlerUtils.show("ExportFileFormatController.exportButtonOnAction", e, this.getStage());
		}
	}
	
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelButtonOnAction(ActionEvent event) throws IOException {
		try {
			this.resetButtonOnAction(event);
			this.getStage().close();
		}catch(Exception e) {
			ExceptionHandlerUtils.show("ExportFileFormatController.cancelButtonOnAction", e, this.getStage());
		}
	}
	
	// Event Listener on Button[#resetButton].onAction
	@FXML
	public void resetButtonOnAction(ActionEvent event) throws IOException {
		try {
			this.getManager().getFileFormatTableViewManager().getController().clearButtonOnAction(event);
			this.exportLocationTextField.setText("");
		}catch(Exception e) {
			ExceptionHandlerUtils.show("ExportFileFormatController.resetButtonOnAction", e, this.getStage());
		}
	}
}
