package viewer.visframe.graphics.property.node;

import graphics.property.node.GraphicsPropertyLeafNode;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import viewer.AbstractViewerController;

/**
 * 
 * @author tanxu
 * 
 */
public class GraphicsPropertyLeafNodeViewerController extends AbstractViewerController<GraphicsPropertyLeafNode<?>>{
	public static final String FXML_FILE_DIR_STRING = "/viewer/visframe/graphics/property/node/GraphicsPropertyLeafNodeViewer.fxml";
	
	
	@Override
	protected void setup() {
		this.nodeInforTextField.setText(this.getViewer().getValue().toString());
	}
	
	@Override
	public Pane getRootContainerPane() {
		return this.rootContainerHBox;
	}
	
	/**
	 * @return the viewer
	 */
	@Override
	public GraphicsPropertyLeafNodeViewer getViewer() {
		return (GraphicsPropertyLeafNodeViewer)this.viewer;
	}
	
	///////////////////////////////////
	@Override
	public void initialize() {
		
	}
	
	@FXML
	private HBox rootContainerHBox;
	@FXML
	private TextField nodeInforTextField;
	@FXML
	private Button viewDetailsButton;

	// Event Listener on Button[#viewDetailsButton].onAction
	@FXML
	public void viewDetailsButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
