package core.pipeline.visscheme.appliedarchive.steps;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class ASelectAppliedVisSchemeStepController2 {
	@FXML
	private HBox rootContainerHBox;
	@FXML
	private TextField appliedVisSchemeUIDTextField;
	@FXML
	private TextField appliedVisSchemeNameTextField;
	@FXML
	private Button viewDetailButton;
	@FXML
	private Button chooseAppliedVisSchemeButton;

	// Event Listener on Button[#viewDetailButton].onAction
	@FXML
	public void viewDetailButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#chooseAppliedVisSchemeButton].onAction
	@FXML
	public void chooseAppliedVisSchemeButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
