package builder.visframe.context.scheme.utils;

import java.sql.SQLException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;

public class CoreShapeCFGEntryController {
	public static final String FXML_FILE_DIR_STRING = "/builder/visframe/context/scheme/utils/CoreShapeCFGEntry.fxml";
	
	//////////////////
	private CoreShapeCFGEntryManager manager;
	
	void setManager(CoreShapeCFGEntryManager manager) {
		this.manager = manager;
		
		//set the UI
		this.nameTextField.setText(this.manager.getCoreShapeCFG().getID().getName().getStringValue());
		
	}
	
	
	public Pane getRootContainerPane() {
		return this.rootContainerHBox;
	}
	
	
	/////////////////////////////
	@FXML
	public void initialize() {
		//
	}
	
	@FXML
	private HBox rootContainerHBox;
	@FXML
	private Button deleteButton;
	@FXML
	private Button viewButton;
	@FXML
	private TextField nameTextField;

	// Event Listener on Button[#deleteButton].onAction
	@FXML
	public void deleteButtonOnAction(ActionEvent event) throws SQLException {
		this.manager.getOwnerVSComponentBuilder().removeCoreShapeCFG(this.manager.getCoreShapeCFG().getID());
	}
	
	// Event Listener on Button[#viewButton].onAction
	@FXML
	public void viewButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}	
